=== happy0wnage/ITRO-Labs/web/xsd/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="device" type="devicesType"/>

    <xs:complexType name="devicesType">
        <xs:sequence>
            <xs:element type="itemType" name="item" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="manufacturer" type="manufacturerType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="manufacturerType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="name" minOccurs="0"/>
            <xs:element type="xs:int" name="founded" minOccurs="0"/>
            <xs:element type="xs:string" name="industry" minOccurs="0"/>
            <xs:element type="xs:string" name="country" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:int" name="id" use="optional"/>
    </xs:complexType>

</xs:schema>

=== happy0wnage/ITRO-Labs/web/xml/device.xml
<?xml version="1.0"?>
<device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/device.xsd">
    <item>
        <model>RJ-13-p</model>
        <price>1</price>
        <manufacturer id="1">
            <name>Asus</name>
            <founded>1989</founded>
            <industry>Computer hardware Electronics</industry>
            <country>Taiwan</country>
        </manufacturer>
    </item>

    <item>
        <model>TT15</model>
        <price>2321</price>
        <manufacturer id="2">
            <name>Asus</name>
            <founded>1989</founded>
            <industry>Computer hardware Electronics</industry>
            <country>Taiwan</country>
        </manufacturer>
    </item>

    <item>
        <model>SM-T</model>
        <price>0</price>
        <manufacturer id="3">
            <name>Asus</name>
            <founded>1989</founded>
            <industry>Computer hardware Electronics</industry>
            <country>Taiwan</country>
        </manufacturer>
    </item>

</device>
